import './globals.css'
import { GlobalContextProvider } from './contexts/store'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <body className="flex flex-col items-center justify-center min-h-screen py-2">
          <main className="flex flex-col items-center justify-center flex-1 px-20 text-center">
            <GlobalContextProvider>
              {children}
            </GlobalContextProvider>
          </main>
        </body>
    </html>
  )
}
